/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package GabrielT

fun isPrime(x: Int, y: Int = 2): Boolean {
    if(x <= 2) {
        return (x == 2)
    }
    if(y * y > x ){
        return true
    }
    if(x % y == 0) {
        return false
    }
    return isPrime(x, y + 1)
}


fun main() {
    val x = 9
    val output =
        if(isPrime(x)) "Prime Number"
        else "Not Prime Number"
    println("Case #1: $output")
}